---
- name: Create new {{ application_name }} project
  command: kubectl create namespace {{ application_name }}

- name: Create new {{ application_name }} app
  command: kubectl run --image {{ openshift_app_image }} {{ application_name }}

- name: Scale {{ application_name }} app
  command: kubectl scale deploy/{{ application_name }} --replicas={{ scale_to }}

- name: Extra service of LoadBalancer type for {{ application_name }} app
  command: kubectl expose deploy/{{ application_name }} --port=80 --target-port=8080
