---
- name: Create new {{ application_name }} project
  command: oc new-project {{ application_name }}

- name: Create new {{ application_name }} app
  command: oc new-app {{ openshift_app_image }} --name {{ application_name }}

- name: Extra service of LoadBalancer type for {{ application_name }} app
  command: oc expose dc/{{ application_name }} --port=80 --target-port=8080 --type LoadBalancer --name {{ application_name }}2
